# IBM Data Science Specialisation Capstone Project Report

### Best Place In Mumbai To Start A Pizza Corner

We had seven prime locations in the city and we had to pick one. That's all the data we had. They were as follows:
<table>
  <tr>
    <th>BranchID</th>
    <th>Location</th>
    <th>Latitude</th>
    <th>Longitude</th>
  </tr>
  <tr>
    <td>IIT001</td>
    <td>IIT Area</td>
    <td>19.134344</td>
    <td>72.890891</td>
  </tr>
  <tr>
    <td>ANE002</td>
    <td>Andheri East</td>
    <td>19.114737</td>
    <td>72.850938</td>
  </tr>
  <tr>
    <td>BRV003</td>
    <td>Borivali</td>
    <td>19.231771</td>
    <td>72.828090</td>
  </tr>
  <tr>
    <td>MUU004</td>
    <td>University Area</td>
    <td>19.102123</td>
    <td>72.804951</td>
  </tr>
  <tr>
    <td>BKC005</td>
    <td>BKC Region</td>
    <td>19.063391</td>
    <td>72.851835</td>
  </tr>
  <tr>
    <td>CHM006</td>
    <td>Chembur East</td>
    <td>19.020779</td>
    <td>72.834109</td>
  </tr>
  <tr>
    <td>CLB007</td>
    <td>Colaba</td>
    <td>18.922700</td>
    <td>72.830696</td>
  </tr>
</table>

So we used the fousquare API in order to get some more information about each location. We obtained nearby venues within a radius of 1km from each location that attracted a significant crowd. The motivation behind this was that any restaurant or pizza corner located at a trending place would subsequently attract more crowd looking for eating places than a pizza corner located at a remote location. 

This is what we got:

<table>
  <tr>
    <th>BranchID</th>
    <th>Location</th>
    <th>Venue</th>
    <th>Venue Latitude</th>
    <th>Venue Longitude</th>
    <th>Venue Category</th>
  </tr>
  <tr>
    <td>IIT001</td>
    <td>IIT Area</td>
    <td>Skky</td>
    <td>19.135841</td>
	<td>72.898494</td>
    <td>Restaurant</td>
  </tr>
  <tr>
 </table>
 
We had about 250 such rows each having a unique venue and each loacted within a 1km radius of one of the seven locations we are looking into.

Then we grouped all the 250 rows into 7 rows, each row for a unique branch and counted the frequency by the category of the venue. For example, say location 1 had 5 chinese restaurants within it's 1km radius. Then we sorted and kept the three most common venue for each branch.

<table>
  <tr>
    <th>BranchID</th>
    <th>1st Most Common Venue</th>
    <th>2nd Most Common Venue</th>
    <th>3rd Most Common Venue</th>
  </tr>
  <tr>
    <td>ANE002</td>
    <td>Indian Restaurant</td>
    <td>Vegetarian / Vegan Restaurant</td>
    <td>Café</td>
  </tr>
  <tr>
    <td>BKC005</td>
    <td>Indian Restaurant</td>
    <td>Pizza Place</td>
    <td>Café</td>
  </tr>
  <tr>
    <td>BRV003</td>
    <td>Restaurant</td>
    <td>Café</td>
    <td>Playground</td>
  </tr>
  <tr>
    <td>CHM006</td>
    <td>Indian Restaurant</td>
    <td>Ice Cream Shop</td>
    <td>Chinese Restaurant</td>
  </tr>
  <tr>
    <td>CLB007</td>
    <td>Indian Restaurant</td>
    <td>Café</td>
    <td>Bar</td>
  </tr>
  <tr>
    <td>IIT001</td>
    <td>Restaurant</td>
    <td>Hotel</td>
    <td>Indian Restaurant</td>
  </tr>
  <tr>
    <td>MUU004</td>
    <td>Accessories Store</td>
    <td>Halal Restaurant</td>
    <td>Deli, Bodega</td>
  </tr>
</table>

We contacted the client again for information from their other outlets regarding how each of these venues affected sales for the outlet. They provided us with the following:

<table>
  <tr>
    <th>Category</th>
    <th>Score</th>
  </tr>
  <tr>
    <td>Chinese Restaurant</td>
    <td>100</td>
  </tr>
  <tr>
    <td>Indian Restaurant</td>
    <td>90</td>
  </tr>
    <tr>
    <td>Coffee Shop</td>
    <td>100</td>
  </tr>
    <tr>
    <td>Pizza Place</td>
    <td>120</td>
  </tr>
    <tr>
    <td>Restaurant: Others</td>
    <td>80</td>
  </tr>
  <tr>
    <td>Ice Cream Shop</td>
    <td>80</td>
  </tr>
    <tr>
    <td>Bar</td>
    <td>100</td>
  </tr>
  <tr>
    <td>Hotel</td>
    <td>100</td>
  </tr>
  <tr>
    <td>Others</td>
    <td>50</td>
  </tr>
</table>

Using this additional information, we were able to rank the locations as per their total score and came up with the optimal location for the restaurant to open their new outlet.

<table>
  <tr>
    <th>BranchID</th>
    <th>Location</th>
    <th>Score</th>
  </tr>
  <tr>
    <td>IIT001</td>
    <td>IIT Area</td>
    <td>270</td>
  </tr>
  <tr>
    <td>ANE002</td>
    <td>Andheri East</td>
    <td>270</td>
  </tr>
  <tr>
    <td>BRV003</td>
    <td>Borivali</td>
    <td>230</td>
  </tr>
  <tr>
    <td>MUU004</td>
    <td>University Area</td>
    <td>180</td>
  </tr>
  <tr>
    <td>BKC005</td>
    <td>BKC Region</td>
    <td>310</td>
  </tr>
  <tr>
    <td>CHM006</td>
    <td>Chembur East</td>
    <td>270</td>
  </tr>
  <tr>
    <td>CLB007</td>
    <td>Colaba</td>
    <td>290</td>
  </tr>
  
  
</table>

So, according to our analysis, an outlet should either be opened at the BKC Region or at Colaba.